# Generated by Django 6.0.6 on 2026-06-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('SIZE', 'Size'), ('FABRIC', 'Fabric Type')], default='SIZE', max_length=10)),
                ('value', models.CharField(help_text='e.g. 38, 40, 42 or Premium Velvet, Pure Wool', max_length=50)),
                ('stock', models.IntegerField(default=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
    ]
