# Generated by Django 6.0.6 on 2026-06-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_notes',
            field=models.TextField(blank=True, help_text='Add step-by-step production updates here.', null=True),
        ),
    ]
