# Generated by Django 6.0.6 on 2026-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_tracking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('payment pending', 'payment pending'), ('payment completed', 'payment completed')], default='payment pending', max_length=30),
        ),
    ]
