# Generated by Django 6.0.6 on 2026-07-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cartitem_cart_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='example: S,M,L,XL,XXL,XXXL', max_length=100),
        ),
    ]
