# Generated by Django 6.0.6 on 2026-07-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.TextField(blank=True, help_text='Example: S:38:27:16.5,M:40:28:17,L:42:29:17.5'),
        ),
    ]
