# Generated by Django 6.0.6 on 2026-07-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Example: S,M,L,XL,XXL,XXXL', max_length=100),
        ),
    ]
