# Generated by Django 6.0.6 on 2026-08-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Set this to show a strikethrough discount price (must be higher than the actual price).', max_digits=10, null=True),
        ),
    ]
